### ISSUE TITLE
mobilenet v2 checkpoint sharing link was wrong

### ISSUE THREAD

**Issue by hunto** [winycg/CIRKD#1]
Dear authors,

Thanks for your great work on CIRKD.

It seems that the pretrained imagenet mbv2 ckpt was linked to a wrong address. Can you fix this?

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/23501718/165014613-c460ff62-da16-42ee-a3f0-522df3c93b6b.png">

**Comment by winycg** [comment]
Hi, thanks for your attention! It seems not a wrong, you may directly download at the upper right corner.
<img width="1179" alt="1650897896(1)" src="https://user-images.githubusercontent.com/16401919/165113434-d4ca04e0-5f77-4a60-9edd-48175ef6a9c3.png">

**Comment by hunto** [comment]
It works. Thank you for your timely reply.
