### ISSUE TITLE
Cannot Download CamVid, PascalVOC dataset

### ISSUE THREAD

**Issue by MaryAhn** [winycg/CIRKD#10]
Hi. 
I would like to reproduce your result in CamVid, PascalVOC dataset.
However, your Baidu drive shows that I have no permission to download.
Would you fix this download problem?

Thanks in advance.
Keonhee.

**Comment by winycg** [comment]
Thanks for your attention. I have tried the Baidu Drive link again in another PC. It seems to work well. If you still meet the problem, I can send the dataset to you via email.

**Comment by MaryAhn** [comment]
Thank you for taking measures. However, I still cannot access the dataset. It will be grateful if you send these two datasets to my email:khahn196@gmail.com.

**Comment by winycg** [comment]
Have done. Please check your email.

**Comment by MaryAhn** [comment]
Thanks!
