### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by swift1988** [winycg/CIRKD#11]
Hi,

Thanks for your excellent work.

Could you release related pretrained models on Pascal VOC.

**Comment by winycg** [comment]
Hi, I review the historical pretrained files and find the pretrained model over distilled deeplabv3_resnet18 with 74.50 mIoU value. If needed, I can send it your personal email. Thanks.

**Comment by swift1988** [comment]
Thanks for your reply!
Here is my email address: conglee4017@gmail.com

**Comment by winycg** [comment]
Have done!

**Comment by swift1988** [comment]
Really Appreciate!

**Comment by winycg** [comment]
You're welcome.
