### ISSUE TITLE
ADE20k

### ISSUE THREAD

**Issue by asiguan** [winycg/CIRKD#12]
Thanks for your contribution!
Can you provide me the Baidu Drive download link of ADE20k and the dataset list of ADE20K.I will be grateful.
My email is 2212108035@stmail.ujs.edu.cn.

**Comment by winycg** [comment]
Hi, Please follow the official ADE20K dataset download link: https://groups.csail.mit.edu/vision/datasets/ADE20K/
My codebase does not need the dataset list of ADE20K and can run the Ade20K experiments directly given the dataset directory.
