### ISSUE TITLE
some question about results

### ISSUE THREAD

**Issue by yhaochen0617** [winycg/CIRKD#15]
When training Cityscapes, log-"semantic_segmentation INFO: Overall validation pixAcc: 95.664, mIoU: 75.386",  meaning the val miou=0.7538 ?
another question, the test miou is computed by the lastest checkpoint or the best checkpoint of the val set？

**Comment by yhaochen0617** [comment]
when training seg with kd,  do you use the imagenet weight as student pretrain ?

**Comment by winycg** [comment]
Yes, this is the validation mIoU. The test miou on Cityscapes is computed by the best checkpoint.

**Comment by yhaochen0617** [comment]
thanks for the reply.
the MobileNetv2 imagenet pertrain link in README looks like mistake, can you update it?

**Comment by yhaochen0617** [comment]
thanks for the reply.
the MobileNetv2 imagenet pertrain link in README looks like mistake, can you update it?

furthmore, when training ctyscapes, are you used https://drive.google.com/file/d/1zUdhYPYCDCclWU3Wo7GbbTlM8ibQ_UC1/view  as teacher model ?  (the model from Performance on Cityscapes of  README )

**Comment by winycg** [comment]
1. Did you download mobilenetv2-imagenet.pth successfully and test it? If you have problems, please show error information.
2. Yeah, we use this checkpoint as the pretrained teacher.

**Comment by yhaochen0617** [comment]
however, the link of mobilenetv2 pretrain in README seems data link instead of model weight, can you check it ?

**Comment by winycg** [comment]
Please do not care the information in the .pth file. Download it directly and load it for running code.
If you still have problems, please refer to http://sceneparsing.csail.mit.edu/model/pretrained_resnet/ for downloading pretrained weights. Thanks.

**Comment by yhaochen0617** [comment]
OK, thank you. Get it~
