### ISSUE TITLE
about ade20k

### ISSUE THREAD

**Issue by yhaochen0617** [winycg/CIRKD#19]
Based on the given teacher model on ade20K,  I found the acc on val is 43.276  instead of 42.7(reported) by running eval.py. can you debug it ?

**Comment by winycg** [comment]
@yhaochen0617 sorry for the delayed response. I think the possible reason may be the batch size. If the total_img_number%batch_size !=0, the sampler would use some other samples to complement the final batch. For example, if the total test image number is 15, batch size is 8, the final batch includes 7 samples, then sampler will use another 1 sample to complement the final batch. The test results are from 16 test image in fact.

**Comment by yhaochen0617** [comment]
Thank you for your reply.

but ade20k val image size is 2000, if test in 8 gpus, it will not happen this.

**Comment by winycg** [comment]
Hi, I  think the gap between  43.276 and 42.7 is small, and your result is acceptable.
