### ISSUE TITLE
About using ADE20K dataset

### ISSUE THREAD

**Issue by jwfanDL** [winycg/CIRKD#20]
Hi, CIRKD is a amazing work on distillation of dense prediction.

I have some problems on using ADE20K. I download ADE20K from https://groups.csail.mit.edu/vision/datasets/ADE20K. 
But when I plug into the code, there exists some problems - I found the folder of dataset I downloaded is hierarchical structure, while  the code for viewing dataset is not. I paste the image as below.
![image](https://user-images.githubusercontent.com/49198978/233009613-95b0345f-3588-42b7-9bd9-a08c3849e24c.png)

![image](https://user-images.githubusercontent.com/49198978/233009672-51988636-5c27-4390-9ba4-6f83693b0982.png)

Are there any scripts that can transform my data to your pattern? Looking forward to your reply.

**Comment by winycg** [comment]
Hi，the new version ADE20K seems having different formulations with the previous version. My ADE20K dataset only includes segmentation .jpg.

**Comment by jwfanDL** [comment]
Thank you so much, do you mind uploading your version?

**Comment by winycg** [comment]
I have sent ADE20K dataset via email. Thx!

**Comment by ZaberKo** [comment]
@winycg May I ask which dataset did you use? [ADEChallengeData2016](http://data.csail.mit.edu/places/ADEchallenge/ADEChallengeData2016.zip) or the official new released [ADE20K](https://groups.csail.mit.edu/vision/datasets/ADE20K) as mentioned above?
