### ISSUE TITLE
ADE20K dataset

### ISSUE THREAD

**Issue by jiyeooong** [winycg/CIRKD#22]
Thanks for your excellent work. :)

https://github.com/winycg/CIRKD/issues/20

I'm having the same problem as above. Could I get a new version of ade20k dataset and pre-trained model parameter(ADE20K, COCO-Stuff-164K) with GoogleDrive?

**Comment by winycg** [comment]
Sorry for the delay, I am too busy recently. You may leave an email and I will sent them to you. Thanks.

**Comment by jiyeooong** [comment]
My email is wldud8946@gmail.com. Thanks!

**Comment by winycg** [comment]
Have sent to you~
