### ISSUE TITLE
Using a large batch size, it is easy to get out of memoroy.

### ISSUE THREAD

**Issue by wohaiyo** [winycg/CIRKD#23]
Nice work!
I want to use a large batch size to train the segmentation model. The current batch size setting is 4 (batch size is set to 3, and the training program can run normally), and it appears out of memory. It looks like the loss function is going to use a lot of memory, so how can I modify it to use a larger batch size?

RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 1; 23.69 GiB total capacity; 22.12 GiB already allocated; 76.19 MiB free; 22.18 GiB reserved in total by PyTorch)

**Comment by winycg** [comment]
https://github.com/winycg/CIRKD/blob/a3f912770d6d16a33f4066a019ef03b1c6ab9288/losses/cirkd_mini_batch.py#LL63C1-L66C37
You may set pooling to down-sample the spatial size to reduce the number of pixels . And you can get similarity matrices with smaller dimension.

**Comment by wohaiyo** [comment]
Thanks a lot, It works!
