### ISSUE TITLE
how to get Test mIoU

### ISSUE THREAD

**Issue by seok-hwa** [winycg/CIRKD#24]
Thanks for the good research.

I am writing to you with one question.
If you look at github, Test mIoU for the Cityscapes dataset is listed, but there is no list of gtFine in test.lst, so I wonder how you experimented.

**Comment by winycg** [comment]
gtFine for test is not available. You should submit the resulting segmentation results to the online evaluation server: 
[https://www.cityscapes-dataset.com/submit/](https://www.cityscapes-dataset.com/submit/)
