### ISSUE TITLE
what difference between the train_cirkd.py and train_cirkd_segformer.py

### ISSUE THREAD

**Issue by GitHubYuxiao** [winycg/CIRKD#25]
what difference between the train_cirkd.py and train_cirkd_segformer.py
If I want to put your method into my semantic segmentation distillation task,what detail should I mind.

**Comment by winycg** [comment]
Hi， train_cirkd_segformer.py is used to distill segformer, train_cirkd.py is used to distill CNN-based segmentation networks.

**Comment by GitHubYuxiao** [comment]
Thank you!
