### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by GitHubYuxiao** [winycg/CIRKD#26]
When I run train_cirkd.py,  it will drop out after the self.criterion_memory_contrast = StudentSegContrast(),it will not run the train()

**Comment by GitHubYuxiao** [comment]
Is it because my computer doesn't have enough memory?

**Comment by winycg** [comment]
Please show your error information.
If your memory is not enough, please set pooling=True at here:
https://github.com/winycg/CIRKD/blob/1a2eb98a02247535aad68fcdf1bd83c34bb68f6d/losses/cirkd_mini_batch.py#L62C1-L67C9

If you have  further issues, please tell me.
