### ISSUE TITLE
The dataset for CamVid and Pascal VOC

### ISSUE THREAD

**Issue by Muyun99** [winycg/CIRKD#6]
Hi, thanks your excellent work.

Since the code style of the repository is really very nice, I am going to use this repository for my algorithm research, could you provide the definition of CamVid and VOC dataset.

I would appreciate it if you could even provide a dataset demo. This really helped me with performance alignment. 

Looking forward to your reply. Thanks!

Best Regards!
Yun

**Comment by winycg** [comment]
Thanks for your attention. I will release the code of CamVid and VOC this week.

**Comment by winycg** [comment]
Hi, I have released the code of CamVid and VOC.
BTW, If our repo helps your research, might you give a star to it?
Thanks.

**Comment by Muyun99** [comment]
Thanks a lot, this repository definitely worth a star!

I will contribute a PR on fp16 training in the near future, which allows the users to run your CIRKD on four RTX 3090s without hyperparameter changes.

Yun

**Comment by Muyun99** [comment]
Hello, do you have the teacher model weight about CamVid and VOC2012Aug?

I notice that it is not provided. I would appreciate it if you could provide the weights. 

Yun

**Comment by winycg** [comment]
Thanks for your attention. I have uploaded pretrained teacher model weights.
