### ISSUE TITLE
The results on Pascal-voc cannot be reproduced

### ISSUE THREAD

**Issue by happycoding1996** [winycg/CIRKD#8]
Hi, 

Thanks for your excellent work.

I have tried reproducing the results on PASCAL-VOC, but inferior results are obtained:

**The model trained with CIRKD (72.6) is even 1% mIoU LOWER than that of the reproduced baseline model (73.7).**

The attached files are the training logs of the baseline and the model of CIRKD trained with Res-101 as the teacher, Res-18 as the student. Both are based on Deeplab-v3.

[deeplabv3_resnet18_voc_baseline_log.txt](https://github.com/winycg/CIRKD/files/9125377/deeplabv3_resnet18_voc_baseline_log.txt)
[voc_deeplabv3_resnet101_resnet18_cirkd_log.txt](https://github.com/winycg/CIRKD/files/9125378/voc_deeplabv3_resnet101_resnet18_cirkd_log.txt)

I have tried using the eval.py to test the best model saved during the training phase, the performance is rather close to that at the last iteration. Also, I have tested the teacher model, and the performance (77.6) matches the one reported on your Github. Now the question is the student model with CIRKD cannot be reproduced.

Could you help figure out where the issue is?

Thanks in advance!

**Comment by winycg** [comment]
Thanks for your attention! On Pascal VOC, the weights of --lambda-memory-pixel and --lambda-memory-region should be 0.01.
Here is my training log (which is not cleaned before the code is released).
[voc_deeplabv3_resnet101_resnet18_cirkd_log.txt](https://github.com/winycg/CIRKD/files/9129690/voc_deeplabv3_resnet101_resnet18_cirkd_log.txt)

**Comment by happycoding1996** [comment]
Thanks for your prompt reply!

I have rerun the experiments with your suggested configuration (setting the weights of --lambda-memory-pixel and --lambda-memory-region to 0.01), and the results are as follows.

[deeplabv3_resnet101_resnet18_log_cirkd_20220720.txt](https://github.com/winycg/CIRKD/files/9155697/deeplabv3_resnet101_resnet18_log_cirkd_20220720.txt)

**The result (73.8) is still comparable to that of the baseline model**, so does it seem like the performance gain brought to the models on PASCAL VOC is relatively incremental compared to that on Cityscapes?

Could you help me figure out the reasons?

Thank you!

**Comment by winycg** [comment]
Thanks for your focus on our work. I also cannot point out the specific problem.  If necessary, you can report your reproduce results in your own research.
