### ISSUE TITLE
A general question about KD

### ISSUE THREAD

**Issue by mylifeasazucchini** [winycg/CIRKD#9]
Is it necessary to train a baseline student model before we start KD ? I ask this because I plan to use a custom small size backbone network and I kinda want to avoid pretraining it on ImageNet. My efforts so far have shown that KD fails when the student model does not have a pretrained backbone, so was this something you also experienced or would you have some advices for me that would enable me to avoid this pretraining ?

**Comment by winycg** [comment]
Hi, I personally think that the small backbone without ImageNet pretraining is OK for seg KD. What is your used backbone? Did you try ResNet-18 or MobileNet?

**Comment by mylifeasazucchini** [comment]
thanks for your quick answer! Much appreicated!

I haven't used your framework for KD yet, I was using CWD so far and as for the backbone I am using this very cool one called EdgeNeXt-XXS (with ~1 Million params)  as the teacher and a self-created lighter version of it called EdgeNeXt-XXXS with (750k params) (https://github.com/mmaaz60/EdgeNeXt) It is basically one of those modern transformers-CNN hybrids. But yeah I would like to keep this issue open while I try out your codebase and methods incase I run into some implementation issue (if that's okay with you!)

Edit 1: My segmentation task is a very simple 3 class segmentation problem, and the Teacher model has an mIoU of 93% already and we would just like to make it slightly smaller so that anyone could use it on mobile phone too! So far the student model with CWD only has about 40 mIoU :(( so that's why I have been digging other repos on this topic!

**Comment by winycg** [comment]
It seems that EdgeNeXt includes transformer-like architecture and we are not sure the conclusion is consistent with CNNs. Towards our experiments, ResNet-18 without ImageNet pretraining can reach 67% from 65% supervised by a ResNet-101 (79%) as the teacher.
